name: DOTNET-DEPLOYMENT
  - name: web
    github:
      repo: darrentan0512/dotnet-deployment
      branch: master
    source_dir: /
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs