name: Build App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Dotnet Buid
        run: dotnet build dotnet-hello-world.csproj

      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.MASTER_TOKEN }}
          app_name: "seal-app"  # Replace with your app name
          app_spec_location: ".do/app.yaml"  # Path to your app spec file

